{{- if not .Values.token.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kink.fullname" . }}
  labels:
    {{ include "kink.labels" . | nindent 4 }}
data:
  token: '{{ .Values.token.value | b64enc }}'
{{- end }}
