apiVersion: kink.meln5674.github.com/v0
Kind: Config
kubernetes:
  kubeconfig: integration-test/kind.kubeconfig
chart:
    chart: ./helm/kink
release:
  upgradeFlags: ['--timeout=15m']
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    worker.securityContext.privileged: "true"
    controlplane.replicaCount: "3"
    worker.replicaCount: "1"
    controlplane.persistence.enabled: "true"
    worker.persistence.enabled: "true" 
    rke2.enabled: "true"
    local-path-provisioner.enabled: "true"
